/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.sergeymitrichev.retailcrm;

import com.github.sergeymitrichev.retailcrm.model.ApiResponse;
import org.junit.jupiter.api.Test;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;

import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

public class RetailCrmApiClientTest {

    public static RetailCrmApiClient client = TestClient.getInstance();

    @Test
    void testGet() {
        ResponseEntity<ApiResponse> response = client.get("customers", ApiResponse.class);
        assertNotNull(response);
        assertEquals(HttpStatus.OK, response.getStatusCode());
        ApiResponse responseBody = response.getBody();
        assertNotNull(responseBody);
        assertTrue(responseBody.isSuccess());
    }

    @Test
    void testPost() {

        ResponseEntity<ApiResponse> response = client.post(
                "customers/create",
                ApiResponse.class,
                Map.of("customer", new ApiResponse()));

        assertNotNull(response);
        assertEquals(HttpStatus.CREATED, response.getStatusCode());
        ApiResponse responseBody = response.getBody();
        assertNotNull(responseBody);
        assertTrue(responseBody.isSuccess());
    }
}
